services:
  mcbot:
    build: .
    container_name: mineflayer_bot
    restart: unless-stopped
    env_file: "stack.env"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: python3 mcbot.py
