version: "3.9"

services:
  mcbot:
    build: .
    container_name: mineflayer_bot
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: python3 mcbot.py